#!/usr/bin/env python

import sys
import argparse
import pushmsg

parser = argparse.ArgumentParser(
    description='Send messages with Pushbullet',
    epilog='For all options, see the line magic help'
)
parser.add_argument('msg', help='Message to send via Pushbullet')
parser.add_argument('--version', action='version', version='0.0.1')


if __name__ == '__main__':
    args = parser.parse_args()
    line = ' '.join(sys.argv[1:])

    p = pushmsg.PushMsg()
    p.pushmsg(line)
