name: pushsmg

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: build (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.6, 3.7, 3.8]
    steps:
    - uses: goanpeca/setup-miniconda@v1
      with:
        miniconda-version: 'latest'
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        channels: conda-forge,bioconda
        activate-environment: pushmsg_env
    - name: conda env setup
      shell: bash -l {0}
      run: |
        conda info -a
        conda install python=${{ matrix.python-version }} ipython
    - uses: actions/checkout@v2
    - name: package install
      shell: bash -l {0}
      run: |
        python -m pip install --upgrade pip
        pip install pushbullet.py
        python setup.py install
    - name: Test
      shell: bash -l {0}
      run: |
        pushmsg -l
        pushmsg_qstat -l
        set -e
        python -c "import IPython; print('IPython %s' % IPython.__version__)";
        python -c "import pushmsg; print('pushmsg %s' % pushmsg.__version__)";
        ipython -c "%load_ext pushmsg";
        ipython -c "%load_ext pushmsg_qstat";
